import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-4 bg-black text-white text-center text-2xl font-bold shadow relative">
          <span className="relative z-10 drop-shadow-lg">Verseye Application</span>
        </header>
        {children}
        <footer className="w-full py-4 bg-gray-100 text-center text-gray-600 text-sm border-t mt-8">
          © {new Date().getFullYear()} All rights reserved
        </footer>
      </body>
    </html>
  );
}
